name       : chrono-date 
version    : 3.0.1
release    : 1
source     :
    - https://github.com/HowardHinnant/date/archive/refs/tags/v3.0.1.tar.gz : 7a390f200f0ccd207e8cff6757e04817c1a0aec3e327b006b7eb451c57ee3538
license    : MIT
component  : programming.devel
summary    : A date and time library based on the C++11/14/17 chrono header 
description: |
    A date and time library based on the C++11/14/17 chrono header 
builddeps  :
    - pkgconfig(libcurl)
patterns   :
    - /*
setup      : |
    %cmake -DBUILD_TZ_LIB=ON
build      : |
    %make
install    : |
    %make_install
